export const projectData = [
  {
    id: 1,
    title: "CHILDREN'S MINISTRY",
    link: "https://allnationsafricanchurch.com/childrens-ministry/",
    text: "We have a very active Children Ministry who’s goal is to share the love of God and make disciples of all children and youth.",
    footer: "2022 · Ministries",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/10/anasda-children-300x200.jpg",
    imgAlt: "CHILDREN",
  },
  {
    id: 2,
    title: "YOUTH MINISTRY",
    link: "https://allnationsafricanchurch.com/youth-department/",
    text: "Our Young Adult Ministry offers inspiration, resources, and opportunities for young adults to grow academically and spiritually in Christ.",
    footer: "2022 · Ministries",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/10/anasda_youth-300x200.jpg",
    imgAlt: "YOUTH",
  },
  {
    id: 3,
    title: "HEALTH MINISTRY",
    link: "https://allnationsafricanchurch.com/health-ministry/",
    text: "Our Mission is to promote health awareness in the church and in the community by providing education of disease prevention.",
    footer: "2022 · Ministries",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/12/health_teaser-300x200.jpg",
    imgAlt: "HEALTH",
  },
  {
    id: 4,
    title: "FROM HEARTS TO HANDS",
    link: "http://fromhearts2hands.org/",
    text: "Just a girl trying to transform the goodwill of our hearts into action in Tanzania",
    footer: "2022 · Missions",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2019/10/IMG_1317-1024x768-400x284.jpg",
    imgAlt: "HEARTS",
  },
  {
    id: 5,
    title: "NOTHING BUT NETS PROJECT",
    link: "https://nothingbutnets.net/donate/",
    text: "A World Health Organization initiative for the fight against malaria.",
    footer: "2022 · Missions",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/10/Malaria_project-400x284.jpg",
    imgAlt: "NETS",
  },
];