export const projectData = [
  {
    id: 1,
    title: "CHILDREN'S MINISTRY",
    link: "https://allnationsafricanchurch.com/childrens-ministry/",
    text: "We have a very active Children Ministry who’s goal is to share the love of God and make disciples of all children and youth.",
    footer: "2022 · Ministries",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/10/anasda-children-300x200.jpg",
    imgAlt: "CHILDREN",
  },
  {
    id: 2,
    title: "YOUTH MINISTRY",
    link: "https://allnationsafricanchurch.com/youth-department/",
    text: "Our Young Adult Ministry offers inspiration, resources, and opportunities for young adults to grow academically and spiritually in Christ.",
    footer: "2022 · Ministries",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/10/anasda_youth-300x200.jpg",
    imgAlt: "YOUTH",
  },
  {
    id: 6,
    title: "COMMUNITY SERVICES",
    link: "https://allnationsafricanchurch.com/community-department/",
    text: "Supports in terms of monetary donations, clothing, Bibles, dry food items, socks, jackets, blankets etc.",
    footer: "2022 · Ministries",
    imgSrc: "http://allnationsafricanchurch.com/wp-content/uploads/2017/12/health_dept.jpg",
    imgAlt: "COMMUNITY",
  },
  {
    id: 3,
    title: "HEALTH MINISTRY",
    link: "https://allnationsafricanchurch.com/health-ministry/",
    text: "Our Mission is to promote health awareness in the church and in the community by providing education of disease prevention.",
    footer: "2022 · Ministries",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/12/health_teaser-300x200.jpg",
    imgAlt: "HEALTH",
  },
  {
    id: 4,
    title: "FROM HEARTS TO HANDS",
    link: "http://fromhearts2hands.org/",
    text: "The goal of From Hearts 2 Hands is to bridge the gap between simple thoughts of goodwill and physical actions of goodwill.",
    footer: "2022 · Missions",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2019/10/IMG_1317-1024x768-400x284.jpg",
    imgAlt: "HEARTS",
  },
  {
    id: 5,
    title: "NOTHING BUT NETS PROJECT",
    link: "https://nothingbutnets.net/donate/",
    text: "Nothing But Nets is a global grassroots campaign to raise awareness, funds, and voices to fight malaria.",
    footer: "2022 · Missions",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/10/Malaria_project-400x284.jpg",
    imgAlt: "NETS",
  },
];

export const linksData = [
  {
    id: 2,
    title: "Bible Study",
    link: "https://ssnet.org/lessons/mobile.html",
    text: "View this week's bible study lesson.",
    footer: "2022 · Ministries",
    imgSrc: "http://allnationsafricanchurch.com/wp-content/uploads/2017/08/BibleandOilLamp.jpg",
    imgAlt: "LEARNING",
  },
  {
    id: 3,
    title: "Weekly Message",
    link: "https://www.youtube.com/channel/UC5jYWyaWW3b0r7MUrK1WVxw/featured",
    text: "View this week's sermon.",
    footer: "2022 · Ministries",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/10/slider-img3.jpg",
    imgAlt: "WATCHING",
  },
  {
    id: 4,
    title: "Tithe and Offering",
    link: "https://adventistgiving.org/#/org/ANPMAL/envelope/start",
    text: "View our giving page.",
    footer: "2022 · Missions",
    imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2017/08/allnations_hero.jpg",
    imgAlt: "GIVING",
  },
  // {
  //   id: 1,
  //   title: "Worship Schedule",
  //   link: "https://demo-church-app.vusa.io/bulletin",
  //   text: "View this week's bulletin.",
  //   footer: "2022 · Ministries",
  //   imgSrc: "https://allnationsafricanchurch.com/wp-content/uploads/2018/08/bulletin.png",
  //   imgAlt: "BULLETIN",
  // },
];